services:
  - type: web
    name: xjtravel-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 web_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ZHIPUAI_API_KEY
        sync: false
