name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create dist directory
        run: |
          mkdir -p dist
          cp -r static/* dist/ || true
          cp -r templates/* dist/ || true
          cp index.html dist/ || true
          
      - name: Create index.html if not exists
        run: |
          if [ ! -f dist/index.html ]; then
            cp templates/index.html dist/index.html || true
          fi
          
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
